version: '3'
services:
    database:
        env_file:
            - .env
        ports:
            - "3306:3306"
        image: mysql:5.7
    app:
        image: node:alpine
        volumes:
            - ./:/app
        working_dir: /app
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - 3000:3000
        command: ./node_modules/.bin/db-migrate up && npm test